---
title: "Diagnostic weekly dashboard"
output: 
  flexdashboard::flex_dashboard:
    css: styles.css
    logo: input/NHS_logo.png
    theme:
      bg: "#FFFFFF"
      fg: "#320871" 
      primary: "#A32C74"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
params:
  report_date: 20240501
  duration: 365
---

```{r setup, include=FALSE}

source('src/functions.R')
# Data ingestion
data = read_csv('data/inter.csv')


# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

Endoscopy
=====================================

Summary column {data-width=100}
-------------------------------------

### Summary metric 1

```{r}
articles <- 50
valueBox(articles, icon = "fa-pencil")
```

### Summary metric 2

```{r}
comments <- 20
valueBox(comments, icon = "fa-comments")
```

### Summary metric 3

```{r}
spam <- 10
valueBox(spam, 
         icon = "fa-trash",
         color = ifelse(spam > 10, "warning", "primary"))
```

### waiting list warning
```{r}
rate <-50
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

Waiting list { data-width=450 .tabset}
-------------------------------------
### Aggregate
```{r}
# Filter data
filtered_data = filter_plot_data(data = data, speciality_group = 'Endoscopy', report_date = params$report_date, duration = params$duration)

# Calculate metric
aggregated_data = filtered_data %>%
  filter(Indicator %in% c('diagnostic_waiting_list', 'wait_list'), 
         !str_detect(Description, 'tci')) %>%
  mutate(
    Length = case_when(
      Description == 'total' ~ 'Over_Six',
      str_detect(Description, 'weeks') ~ 'Under_Six'
    )
  ) %>%
  group_by(Date, Length) %>%
  summarise(Activity = sum(Activity)) %>%
  ungroup() %>%
  pivot_wider(id_cols = Date, names_from = Length, values_from = Activity) %>%
  mutate(Total = Over_Six + Under_Six,
         Prop_over_six = round(Over_Six/Total*100,0)) 


plot = ggplot(aggregated_data, aes(x=Date, y = Over_Six, label = paste0(Over_Six, '\n(', Prop_over_six, '%)'))) +
  geom_bar( stat="identity", fill =  "#1B9B9D") + 
  geom_text(position = position_stack(vjust=0.5), colour = 'white')+
  theme_nclicb()+
  ggtitle('Whatever this is supposed to show...')+
  theme(legend.position = 'none',
         )+
  scale_x_date(date_breaks = "1 week", date_labels = "%d-%b") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x="Week commencing",
       y ="Over 6 weeks (people)",
       title="Endoscopy waiting list",
       subtitle="6+ weeks")

ggplotly(plot)
```

### By provider
```{r}
# Filter data
filtered_data = filter_plot_data(data = data, speciality_group = 'Endoscopy', indicator = 'diagnostic_waiting_list', report_date = params$report_date, duration = params$duration)

# Calculate metric
aggregated_data = filtered_data %>%
  filter(Description == 'total')%>%
  group_by(Date, Provider) %>%
  summarise(Activity = sum(Activity)) %>%
  ungroup() 

# Plot data
plot = line_plot_time(aggregated_data, Provider, 'Number of cases', 'Diagnostic 6+ Week waits per provider') +
  scale_x_date(date_breaks = "1 week", date_labels = "%d-%b") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x="Week commencing",
       y ="Over 6 weeks (people)",
       title="Endoscopy waiting list",
       subtitle="6+ weeks")

ggplotly(plot)
```

### Individual provider
```{r}
# Filter data
filtered_data = filter_plot_data(data = data, speciality_group = 'Endoscopy', indicator = 'diagnostic_waiting_list', report_date = params$report_date, duration = params$duration)

# Calculate metric
aggregated_data = filtered_data %>%
  filter(Description == 'total')%>%
  group_by(Date, Provider) %>%
  summarise(Activity = sum(Activity)) %>%
  ungroup()  %>%
  filter(Activity>0)

# Plot data
plot = line_plot_time(aggregated_data, Provider, 'Number of cases', 'Diagnostic 6+ Week waits per provider') + 
  facet_wrap(~Provider, scales = 'free_y')+
  theme(panel.spacing = unit(0.5, "lines"))+
  scale_x_date(date_breaks = "1 week", date_labels = "%d-%b") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x="Week commencing",
       y ="Over 6 weeks (people)",
       title="Endoscopy waiting list",
       subtitle="6+ weeks")

ggplotly(plot)
```
Activity { data-width=450 .tabset}
-------------------------------------

### Aggregate
```{r}
# Filter data
filtered_data = filter_plot_data(data = data, speciality_group = 'Endoscopy', indicator = 'activity', report_date = params$report_date, duration = params$duration)

# Calculate metric
aggregated_data = filtered_data %>%
  group_by(Date,Description) %>%
  summarise(Activity = sum(Activity)) %>%
  ungroup() 


plot = ggplot(aggregated_data, aes(x=Date, y = Activity, group = Description, color = Description, label = paste0(Description, ': ', Activity)))+
  geom_line() + 
  theme_nclicb()+
  theme(legend.position = 'none',
         )+
  scale_x_date(date_breaks = "1 week", date_labels = "%d-%b") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x="Week commencing",
       y ="Activity (procedures)",
       title="Endoscopy Activity",
       subtitle="Total")

ggplotly(plot)
```

### By provider
```{r}
# Filter data
filtered_data = filter_plot_data(data = data, speciality_group = 'Endoscopy', indicator = 'activity', report_date = params$report_date, duration = params$duration)

# Calculate metric
aggregated_data = filtered_data %>%
  filter(Description != 'total')%>%
  group_by(Date, Provider) %>%
  summarise(Activity = sum(Activity)) %>%
  ungroup() 

# Plot data
plot = line_plot_time(aggregated_data, Provider, 'Number of procedures', 'Weekly endoscopy activity') +
  scale_x_date(date_breaks = "1 week", date_labels = "%d-%b") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x="Week commencing",
       y ="Activity (procedures)",
       title="Endoscopy Activity",
       subtitle="Total provider")

ggplotly(plot)
```

### Individual provider
```{r}
# Filter data
filtered_data = filter_plot_data(data = data, speciality_group = 'Endoscopy', indicator = 'activity', report_date = params$report_date, duration = params$duration)

# Calculate metric
aggregated_data = filtered_data %>%
  filter(Description != 'total')%>%
  group_by(Date,Provider, Description) %>%
  summarise(Activity = sum(Activity)) %>%
  ungroup() %>%
  filter(Activity >0)


# Plot data
plot = ggplot(aggregated_data, aes(fill=Description, y=Activity, x=Date)) + 
    geom_bar(position="fill", stat="identity")+
  theme_nclicb()+
  scale_x_date(date_breaks = "1 week", date_labels = "%d-%b") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x="Week commencing",
       y ="Activity (procedures)",
       title="Endoscopy Activity",
       subtitle="Total provider")+
  facet_wrap(~Provider)

ggplotly(plot)
```

Imaging
=====================================
## Column {.tabset data-width="650"}

### Chart A

```{r}

```

### Chart B

```{r}

```

## Column {data-width="350"}

### Chart C

```{r}

```

### Chart D

```{r}


```
QA
=====================================

