---
title: "Ingest_Flex_Freeze"
author: "Arush Mohan"
date: "`r Sys.Date()`"
output: html_document
params:
  report_date: 20240609
  freeze_window: 7
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('src/functions.R')

```



## Defining folder directories

```{r}

# Extract the date from the main folder name
main_folder_date <- as.Date(ymd(params$report_date), format = "%Y-%m-%d")

# Calculate the date for freeze files
freeze_date <- ymd(params$report_date) - days(params$freeze_window)

# Define folders
main_folder <- paste0('data/', main_folder_date)
dir_path_flex <- file.path(main_folder, "Flex")
dir_path_freeze <- file.path(main_folder, "Freeze")

```


## Listing the files in the directory

```{r}

# List all Excel files in the directories
file_list_flex <- list.files(path = dir_path_flex, pattern = "*.xlsx", full.names = TRUE)
file_list_freeze <- list.files(path = dir_path_freeze, pattern = "*.xlsx", full.names = TRUE)

```



## Combining file lists and differentiating flex/freeze

```{r}

# Combine both file lists and add a DataType column
file_list <- tibble(
  file_path = c(file_list_flex, file_list_freeze),
  DataType = c(rep("flex", length(file_list_flex)), rep("freeze", length(file_list_freeze))),
  ReportDate = c(rep(main_folder_date, length(file_list_flex)), rep(freeze_date, length(file_list_freeze)))
) %>%
  mutate(provider_name = text_normalisation(str_extract(basename(file_path), "^[^_]+"))) 

```



## Defining columns and sheet parameters

``` {r}
# Read the column names
indicator_list <- read_csv("input/Provider_indicator_list.csv")
provider_list <- file_list %>%
  select(provider_name) %>%
  distinct()

# Build full list
Indicators <- expand_grid(Provider = provider_list$provider_name, Indicator = indicator_list$Indicator)

# Modifications
## read
Indicator_edits <- read_csv('input/Provider_inconsistency_adjustment.csv')
  
## remove missing
Missing_indicators <- Indicator_edits %>%
  filter(Issue == 'Missing')

Indicators <- Indicators %>%
  filter(!paste0(Provider, '_', Indicator) %in% paste0(Missing_indicators$Provider, '_', Missing_indicators$Indicator))

## Add new - NEEDS TESTING
New_indicators <- Indicator_edits %>%
  filter(Issue == 'Additional') %>%
  select(Provider, Indicator)

Indicators <- Indicators %>%
  bind_rows(New_indicators)

# Read combined sheet parameters and sheet names from CSV
sheet_parameters <- read_csv("input/Sheet_parameters.csv") %>%
  mutate(Provider  = text_normalisation(Provider))

```

## Extracting the data

```{r}
# Read and combine all files into one data frame
combined_data <- file_list %>%
  mutate(data = map(.x = file_path, ~ingest_raw_data_file(file_path = .x))) %>% # function in function.R
  #filter(map_lgl(data, ~ !is.null(.x))) %>% # I don't think you need this
  unnest(cols = c(data)) %>%
  select(-file_path)
  

```
## Processing for upload
```{r}
#speciality_grouping <- read_csv('input/grouping.csv') # commented out, should be added in visualisation only

combined_data<- combined_data %>%
  separate_wider_delim(Indicator, '-', names = c('Indicator','Description'), too_few = 'align_start') %>% # split indicators
  mutate(Description = replace_na(Description, 'None'))#%>% 
  #left_join(speciality_grouping) # adding context # commented out, should be added in visualisation only
```

```{r}

# Write combined dataset to a new Excel file
write_xlsx(combined_data, paste0('output/', "combined_dataset_", as.Date(params$report_date), ".xlsx"))

```



## Add upload to sandpit sections - override for freeze, simple upload for flex
```{r}

# delete last week and upload all?
#The function will replace last week's flex data with freeze data and append the new flex data

con <- dbConnect(odbc::odbc(), 
                 dsn = "SANDPIT",
                 database = "Data_Lab_NCL",
                 TrustedConnection = TRUE)

upload_combined_data <- function(con, combined_data) {
  # Begin a transaction
  dbBegin(con)
  
  # Separate the data into flex and freeze
  flex_data <- combined_data %>% filter(DataType == "flex")
  freeze_data <- combined_data %>% filter(DataType == "freeze")
  
  # Replace existing flex data with freeze data based on provider_name and ReportDate
  for (i in 1:nrow(freeze_data)) {
    provider <- freeze_data$provider_name[i]
    report_date <- freeze_data$ReportDate[i]
    
    # Check if there is matching flex data in the database
    existing_flex <- dbGetQuery(con, 
                                paste("SELECT COUNT(*) FROM [Data_Lab_NCL].[MohanA].[DashboardTest] 
                                       WHERE DataType = 'flex' AND provider_name = '", provider, 
                                       "' AND ReportDate = '", report_date, "'", sep = ""))
    
    # If there is matching flex data, delete it
    if (existing_flex[1, 1] > 0) {
      delete_statement <- paste("DELETE FROM [Data_Lab_NCL].[MohanA].[DashboardTest] 
                                 WHERE DataType = 'flex' AND provider_name = '", provider, 
                                 "' AND ReportDate = '", report_date, "'", sep = "")
      dbSendStatement(con, delete_statement) %>% dbClearResult()
    }
  }
  
  # Upload the freeze data to the database
  dbWriteTable(con, Id(schema = "MohanA", table = "DashboardTest"), freeze_data, append = TRUE, row.names = FALSE)
  
  # Upload the new flex data to the database
  dbWriteTable(con, Id(schema = "MohanA", table = "DashboardTest"), flex_data, append = TRUE, row.names = FALSE)
  
  # Commit the transaction
  dbCommit(con)
}



```



```{r}

upload_combined_data(con, combined_data)

```


```{r}

dbDisconnect(con)

```